Finished porting of "t_pub/sub_delay"
ZettaScaleLabs/zenoh-perf pull request #12
Opened 2022-04-24 07:58 UTC by eddie9712

* Replace structopt to clap in `t_pub/sub_delay.rs`
* Update the usage of zenoh in `t_pub/sub_delay.rs`
* Add payload size checking (payload size should >= 24)
* Cargo fmt

- [ ] Compilation passed with command cargo build --bin t_pub(sub)
_delay
- [ ] Verified by the following commands: `./t_sub_delay -e tcp/127.0.0.1:7447 -m peer`,
`./t_ping -m peer -p 24 -i 1 -e tcp/127.0.0.1:7447`
- [ ] Checked with Cargo clippy

2022-04-25 01:02 UTC, william-wyliang commented
Also invite @YuanYuYuan to review.

2022-04-25 02:03 UTC, YuanYuYuan commented on latency/src/bin/t_pub_delay.rs
> +        let key = "/test/ping".into();
A plain `into` is meaningless. I suggest you can move to where `key` is used.

2022-04-25 06:27 UTC, eddie9712 commented on latency/src/bin/t_pub_delay.rs
> +        let key = "/test/ping".into();
Thanks, I will edit it.

2022-04-25 10:22 UTC, william-wyliang requested changes
Suggest to do some code refactoring. See the inline comments.

2022-04-25 10:22 UTC, william-wyliang commented on latency/src/bin/t_pub_delay.rs
> +        if opt.payload < 24 {
Good to check here.

2022-04-25 10:22 UTC, william-wyliang commented on latency/src/bin/t_sub_delay.rs
> +                }
Consider to refactor this segment of code. Checking the success of `read_exact()` of `count` and `now_pub` all before `now_sub`.

2022-04-26 00:15 UTC, eddie9712 commented on latency/src/bin/t_pub_delay.rs
> +#[clap(name = "t_pub_delay")]
I think it is a typo, the `name` is the binary name displayed in help messages.

2022-04-26 02:38 UTC, eddie9712 commented on latency/src/bin/t_sub_delay.rs
> +                }
Ok, I will try to reduce the indent of this segment.

2022-04-26 02:58 UTC, william-wyliang approved these changes

2022-04-26 02:59 UTC, merged