Source codes used for the comparison in the blog
ZettaScaleLabs/zenoh-perf pull request #19
Opened 2023-03-08 17:24 UTC by YuanYuYuan

This PR includes the codes used for the throughput & latency benchmarking article to be published on the blog.

- Zenoh
- Kafka
- MQTT
- CycloneDDS

Note that this PR wouldn't pass the CI since the other codes are still in the previous version. An update to align the API to 0.7.0-rc will be submitted as another PR later.

2023-03-09 07:59 UTC, gabrik requested changes
Few things here and there.
I do not really like the output format.

I think something like:
`<protocol>,[lantecy|througput],[interval|payload],<value>,<unit>` 

would be better, and I think more comments on why things in kafka are done the way they are would help everyone to understand better.

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/README.md
> +# cat 2022-07-28T11-00-01+08-00_latency/payload-16_interval-0.001/1_cargo run --bin kafka_ping --release -- -p 16 -i 0
From the code, the output of `kafka_ping` seems different: `<interval>,<value>`

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/README.md
> +kafka,DUMMY_SCENARIO,throughput,DUMMY_NAME,16,171.431
Why it is there a `.` in the values?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/scripts/files/config-cluster/server.properties
> +num.network.threads=3
Why 3?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_ping/main.rs
> +            println!("{},{}", opts.interval, info.rtt.as_micros() / 2);
I prefer to always put the unit used for the value, in this case: `<protocol>,<interval>,<rtt>,us` 
Otherwise, just by looking at the data, it is impossible to understand.

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_ping/main.rs
> +    // try_join!(producer, consumer)?;
Remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/rust-toolchain.toml
> +channel = "1.62.0"
I guess `1.62.0` because of Zenoh?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_ping/opts.rs
> +}
This is not being used. Remove it

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pong/main.rs
> +                Err(err) => return Err(err.into()),
Can you explain why this is needed in a comment please?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pong/main.rs
> +        // .set("enable.auto.commit", "false")
Remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pong/main.rs
> +// }
Remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pub_thr/main.rs
> +    //     .create()?;
Remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pub_thr/main.rs
> +        let payload = generate_payload(producer_id, msg_idx as u32, opts.payload_size);
As far as I recall Zenoh performance tests the payload is generated only once and then stored in `Arc<Vec<u8>>`.
While here it seems to me that we are generating it all the time, I think it is not fair.

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_pub_thr/opts.rs
> +}
It there a peer mode in Kafka?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_sub_thr/main.rs
> +            // .set("enable.partition.eof", "false")
remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_sub_thr/main.rs
> +            // .set("enable.auto.commit", "false")
remove

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_sub_thr/main.rs
> +        let info = match parse_payload(payload, opts.payload_size) {
Why we need to parse it?

2023-03-09 07:59 UTC, gabrik commented on comparison/kafka/src/kafka_sub_thr/opts.rs
> +}
Again, it seems that it is not used, in this case remove it.

2023-03-09 07:59 UTC, gabrik commented on comparison/mqtt/throughput/mqtt_pub_thr.c
> +        // }
Remove

2023-03-09 07:59 UTC, gabrik commented on comparison/zenoh/src/bin/zenoh_pub_thr.rs
> +    mode: WhatAmI,
I'm thinking if it is not better to pass a Zenoh configuration file, @Mallets?

2023-03-09 07:59 UTC, gabrik commented on comparison/zenoh/src/bin/zenoh_sub_thr.rs
> +            println!("{},{:.3}", payload, c as f64 * 1_000_000.0 / elapsed);
Here I would prefer `<protocol>,<payload>,<value>,msgs` where msgs is the unit, but on the latter I can live without it.

2023-03-09 07:59 UTC, gabrik commented on comparison/cyclonedds/throughput/subscriber.c
> +            printf ("%lu,%.2f\n", payloadSize, (double)numSamples / deltaTime * DDS_NSECS_IN_SEC);
`<protocol>,<payload>,<value>,msgs`

2023-03-09 07:59 UTC, gabrik commented on comparison/mqtt/latency/mqtt_ping.c
> +                printf("%.10f,%ld\n", interveal, elapsed / 2);
`<protocol>,<interval>,<value>,<unit>`

2023-03-09 11:25 UTC, gabrik commented on comparison/cyclonedds/throughput/publisher.c
> +    }
Not a real comment, just to keep track of how we generate the payloads.
Here is generated once and sent multiple times.

2023-03-09 11:25 UTC, gabrik commented on comparison/mqtt/throughput/mqtt_pub_thr.c
> +            pubmsg.retained = 0;
Not a real comment, just to keep track of how we generate the payloads.
Here is generated at each iteration.

2023-03-09 11:25 UTC, gabrik commented on comparison/zenoh/src/bin/zenoh_pub_thr.rs
> +        .into();
Not a real comment, just to keep track of how we generate the payloads.
Here is generated once and sent multiple times.

2023-03-10 07:42 UTC, YuanYuYuan commented on comparison/zenoh/Makefile
> +	@rm -f Cargo.lock &> /dev/null
This is for ease of using [zenoh-test](https://github.com/YuanYuYuan/zenoh-tests/blob/blog/comparison/README.md#build-all-the-source-codes).

2023-03-10 07:43 UTC, YuanYuYuan commented on comparison/cyclonedds/throughput/publisher.c
> +    }
Yes, it is.

2023-03-10 07:46 UTC, YuanYuYuan commented on comparison/mqtt/throughput/mqtt_pub_thr.c
> +            pubmsg.retained = 0;
Yes, the message is regenerated every time. But the payload data is copied as zenoh does (`publisher.put(data.clone()).res().unwrap();`), and thus the zenoh message is regenerated every time.

2023-03-10 07:46 UTC, YuanYuYuan commented on comparison/zenoh/src/bin/zenoh_pub_thr.rs
> +        .into();
Yes, it is.

2023-03-10 08:41 UTC, gabrik commented on comparison/mqtt/throughput/mqtt_pub_thr.c
> +            pubmsg.retained = 0;
Perfect I've missed that

2023-03-10 09:56 UTC, jerry73204 commented on comparison/kafka/scripts/files/config-cluster/server.properties
> +num.network.threads=3
This is the default setting. Increasing it can improve performance. I'm not sure we're supposed to tune it up because this parameter depends on your actual server settings.

2023-03-14 12:59 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_ping/main.rs
> +    // try_join!(producer, consumer)?;
Removed.

2023-03-14 12:59 UTC, YuanYuYuan commented on comparison/kafka/rust-toolchain.toml
> +channel = "1.62.0"
Has been removed.

2023-03-14 13:04 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pong/main.rs
> +        // .set("enable.auto.commit", "false")
Removed.

2023-03-14 13:04 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pong/main.rs
> +// }
Removed.

2023-03-14 13:05 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_sub_thr/main.rs
> +            // .set("enable.auto.commit", "false")
Removed.

2023-03-14 13:06 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_sub_thr/opts.rs
> +}
Removed.

2023-03-14 13:08 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_sub_thr/main.rs
> +            // .set("enable.partition.eof", "false")
Removed.

2023-03-14 13:12 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pub_thr/main.rs
> +    //     .create()?;
Removed.

2023-03-14 13:12 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pub_thr/main.rs
> +        let payload = generate_payload(producer_id, msg_idx as u32, opts.payload_size);
Has been discussed in Discord.

2023-03-14 13:13 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pub_thr/opts.rs
> +}
It's redundant. Removed.

2023-03-14 13:15 UTC, YuanYuYuan commented on comparison/mqtt/throughput/mqtt_pub_thr.c
> +        // }
Removed.

2023-03-14 13:20 UTC, YuanYuYuan commented on comparison/kafka/README.md
> +kafka,DUMMY_SCENARIO,throughput,DUMMY_NAME,16,171.431
The document is outdated and has been removed.

2023-03-14 13:20 UTC, YuanYuYuan commented on comparison/kafka/README.md
> +# cat 2022-07-28T11-00-01+08-00_latency/payload-16_interval-0.001/1_cargo run --bin kafka_ping --release -- -p 16 -i 0
The document is outdated and has been removed.

2023-03-14 13:25 UTC, YuanYuYuan commented on comparison/kafka/src/kafka_pong/main.rs
> +                Err(err) => return Err(err.into()),
If I remember correctly, this prevents the program from crashing if the target topic hasn't been created yet.

2023-03-14 14:27 UTC, YuanYuYuan commented
About the concern of printing format, we have (at least) three ways co-existing right now. 

Take the throughput as an example

1. Orginal zenoh-perf by Luca: protocol, scenario, throughput, name, payload_size, value
2. zenoh-pico-perf by Carlos: layer, name, test, scenario, payload_size, value
3. This PR: payload_size, value (, which has its corresponding analysis at [zenoh-tests](https://github.com/YuanYuYuan/zenoh-tests/tree/blog/comparison))

At first, we just want to make this PR (as well as previous PR to zenoh-pico-perf) be compatible with 1. and 3. Therefore previous zenoh-tests codes are still runnable with the zenoh-perf. I mean those tables containing "scenario", "name", and "protocol" columns. 

The design of the current printing format is to keep it as simple as possible and let the users append the experiment info by themselves. For instance, I want to benchmark the throughput between two machines of the protocols CycloneDDS and Zenoh. Then I run the zenoh-tests and have the following default experiment folder hierarchy.
```bash
results/timestamp/{CycloneDDS, Zenoh}.csv 
```
of which content is printed in "payload, value".

The points  are

1. We can modify the default folder name "results/timestamp" with some customized ones like "results/throughput/two-machines/timestamp" to log more info related to that experiment. (Note that this info actually depends on the usage with zenoh-tests not on zenoh-perf itself, since we can always fine-tune the zenoh-perf with different scripts like [these zenoh variants](https://github.com/YuanYuYuan/zenoh-tests/tree/blog/comparison/throughput/scripts)). That's why we remove the columns "scenario, name, protocol".

2. The parsing of the results is convenient if we only log the minimal information. Any confusion about the output format should be resolved by the README.md with the zenoh-perf codes. Like the pattern of FP,  we had already described the function behavior completely, users with zenoh-tests or standalone ones should be aware of the information.  For example, instead of logging the unit of latency, we explicitly write it down in a document and the analysis from zenoh-tests should follow the format. (The cost is the same with logging the unit inside the output, but the dependence is much clear.) That's why we don't want to log additional info into the log.

2023-03-15 09:09 UTC, YuanYuYuan commented
I've added some docs:

1. zenoh-perf/comparison/{MQTT, Kafka, Zenoh, CycloneDDS}/README.md: Guide for usage and output format.
2. zeonh-perf/comparison/README.md: Links to codes and tabular data

2023-03-16 10:08 UTC, gabrik commented
Thanks for the explanation on the output format, I'm fine the way it is, at the end my preference was driven by the way I usually write the parsers.
So I'm ok with the format provided in the PR

2023-03-17 05:05 UTC, william-wyliang commented
> Thanks, @gabrik! Then I think all the issues have been discussed and resolved. @william-wyliang , do you have any comments on it? Otherwise, let's get ready to merge this PR!

It's all good for me. Will merge this PR.

2023-03-17 05:05 UTC, merged